# -*- coding: utf-8 -*-
"""Pythonbasic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btfaOIkIAbege4mvX4k4xu435y9lcuPS
"""

print("Assignment 1")

li=[int(i) for i in input("Enter Values:").split()]
li.sort()
print(li)

li.reverse()
print(li)

print(type(li))

